name: Update GitHub Stats

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 * * * *" # Runs every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Generate Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          token: ${{ secrets.Stats_Automation_token }}
