name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update README with Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          token: ${{ secrets.automation_token }}
